name: First Workflow

on: 
 workflow_dispatch

jobs: 
 firstjob:
  runs-on: self-hosted
  steps:
  - name: First job
    run: echo The first job!
  
  - name: Checkout
    uses: actions/checkout@v2.6.0
    with:
     repository: ${{ github.repository }}

  - name: Create your own action
    id: greeting
    uses: actions/hello-world-javscrpt-action@main
    with:
     who-to-greet: "Sahil Suri"
     
  - name: time
    run: |
     echo "The time of greeting was at: ${{step.greeting.outputs.time}}"
    


