name: First Workflow

on: 
 workflow_dispatch

jobs: 
 firstjob:
  runs-on: self-hosted
  steps:
  - name: First job
    run: echo The first job!
  
  - name: Checkout
    uses: actions/checkout@v2.6.0
    with:
     repository: ${{ github.repository }}




